name: Install Solana

inputs:
  version:
    description: The Solana version to install
    required: true
    default: 'stable'
  cache:
    description: Whether the downloaded Solana release should be cached
    required: true
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Cache Solana
      id: cache
      if: inputs.cache == 'true'
      uses: buildjet/cache@v3
      with:
        path: |
          ~/.local/share/solana/install/releases/${{ inputs.version }}
          ~/.cache/solana
        key: ${{ runner.os }}-solana-v${{ inputs.version }}

    - name: Install Solana
      if: inputs.cache != 'true' || steps.cache.outputs.cache-hit != 'true'
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v${{ inputs.version }}/install)"
      shell: bash

    - name: Set Active Solana Version
      run: |
        rm -f "$HOME/.local/share/solana/install/active_release"
        ln -s "$HOME/.local/share/solana/install/releases/${{ inputs.version }}/solana-release" "$HOME/.local/share/solana/install/active_release"
      shell: bash

    - name: Add Solana bin to Path
      run: |
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash

    - name: Verify Solana install
      run: |
        solana --version
      shell: bash
