[workspace]
resolver = "2"
members = [
  "clients/rust/asset",
  "clients/rust/bridge",
  "programs/asset/interface",
  "programs/asset/program",
  "programs/asset/types",
  "programs/bridge",
  "programs/proxy",
]
