name: Build Programs

on:
  workflow_call:
    inputs:
      rust:
        type: string
      solana:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.70.0
        required: true
        type: string
      solana:
        description: Solana version
        default: 1.16.18
        required: true
        type: string

env:
  CACHE: true

jobs:
  build_programs:
    name: Build
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: nifty-oss/actions/install-rust@v1
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Install Solana
        uses: nifty-oss/actions/install-solana@v1
        with:
          version: ${{ inputs.solana || env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install Node.js
        uses: nifty-oss/actions/install-node-with-pnpm@v1
        with:
            version: ${{ env.NODE_VERSION }}
            cache: ${{ env.CACHE }}
            dependencies: true

      - name: Cache program dependencies
        if: env.CACHE == 'true'
        uses: nifty-oss/actions/buildjet-cache-crate@v1
        with:
          folder: '.'
          key: programs

      - name: Build programs
        shell: bash
        working-directory: configs/scripts/program
        run: ./build.sh
        env:
          PROGRAMS: ${{ env.PROGRAMS }}

      - name: Upload program builds
        uses: actions/upload-artifact@v4
        with:
          name: program-builds
          # First wildcard ensures exported paths are consistently under the programs folder.
          path: ./program*/.bin/*.so
          if-no-files-found: error
