name: Build Rust CLI

on:
  workflow_call:
    inputs:
      rust:
        type: string
      solana:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.70.0
        required: true
        type: string
      solana:
        description: Solana version
        default: 1.16.18
        required: true
        type: string

env:
  CACHE: true

jobs:
  build_sdk:
    name: Build
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: nifty-oss/actions/install-rust@v1
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Install Solana
        uses: nifty-oss/actions/install-solana@v1
        with:
          version: ${{ inputs.solana || env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache Rust CLI dependencies
        uses: nifty-oss/actions/buildjet-cache-crate@v1
        with:
          folder: '.'
          key: rust-cli-test

      - name: Build Rust CLI
        shell: bash
        working-directory: clients/cli
        run: cargo build --all-features --release

      - name: Upload Rust CLI builds
        uses: actions/upload-artifact@v4
        with:
          name: rust-cli-builds
          # First wildcard ensures exported paths are consistently under the clients folder.
          path: ./client*/cli/target/release/*nifty*
          if-no-files-found: error
