name: Test JS client

on:
  workflow_call:
    inputs:
      client_matrix:
        type: string

env:
  CACHE: true

jobs:
  test:
    name: Test
    runs-on: buildjet-8vcpu-ubuntu-2204
    strategy:
      matrix:
        node: ["18.x", "20.x"]
        client: ${{ fromJson(inputs.client_matrix) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Start validator
        uses: nifty-oss/actions/start-validator@v1
        with:
          node: ${{ matrix.node }}
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install dependencies
        uses: nifty-oss/actions/install-node-dependencies@v1
        with:
          folder: ./clients/js
          cache: ${{ env.CACHE }}
          key: client-js

      - name: Build
        working-directory: ./clients/js/${{ matrix.client }}
        run: pnpm build

      - name: Test
        working-directory: ./clients/js/${{ matrix.client }}
        run: pnpm test

  lint:
    name: Lint
    runs-on: buildjet-8vcpu-ubuntu-2204
    strategy:
      matrix:
        client: ${{ fromJson(inputs.client_matrix) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Node.js
        uses: nifty-oss/actions/install-node-with-pnpm@v1
        with:
          version: ${{ env.NODE_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install dependencies
        uses: nifty-oss/actions/install-node-dependencies@v1
        with:
          folder: ./clients/js
          cache: ${{ env.CACHE }}
          key: client-js

      - name: Format
        working-directory: ./clients/js/${{ matrix.client }}
        run: pnpm format

      - name: Lint
        working-directory: ./clients/js/${{ matrix.client }}
        run: pnpm lint
