name: Test Rust Client

on:
  workflow_call:
    inputs:
      client_matrix:
        type: string

env:
  CACHE: true

jobs:
  test_sdk:
    name: Test
    runs-on: buildjet-8vcpu-ubuntu-2204
    strategy:
      matrix:
        client: ${{ fromJson(inputs.client_matrix) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: nifty-oss/actions/install-rust@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Solana
        uses: nifty-oss/actions/install-solana@v1
        with:
          version: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache Rust client test dependencies
        uses: nifty-oss/actions/buildjet-cache-crate@v1
        with:
          folder: '.'
          key: ${{ matrix.client }}-rust-client-test

      - name: Download program builds
        uses: actions/download-artifact@v4
        with:
          name: program-builds

      - name: Run tests
        shell: bash
        working-directory: configs/scripts/client
        run: RUST_LOG=error ./test-rust.sh ${{ matrix.client }}
